sudo: required
services:
  - docker
before_install:
  - ./scripts/travis-docker-auth.sh
install:
  - ./scripts/travis-build-image.sh
script:
  - ./scripts/travis-test-app.sh
  - ./scripts/travis-test-image.sh
after_success:
  - ./scripts/travis-push-image.sh
notifications:
  slack:
    secure: qThWSSDhhcLDyYXmGuHYR/5P7eHNsU/xAumx85U4JoiTBP2+KcAVfhdziO0SWg18+3odXrhMQEEmj2inONj7+Ug12HGJEpNO7GdgJCnvlTI5/QnsH6vlqDjVEapRPCZpenW3oxqsBLl/wjaez1NvHtfJIUIPVNivvbjvWVvFGyk=
deploy:
  provider: script
  script: scripts/deploy-wrap.sh
  skip_cleanup: true
  on:
    branch:
    - master
    - test
