---
version: '3.7'

# This is a development version which enables the application to run
# using the production-ready image to test locally.

services:
  api:
    image: cybernetisk/in-backend:latest
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    init: true
    volumes:
      # Mount in this folder as it is used to hold local settings
      # and also the sqlite database used for local development.
      - ./cyb_oko:/app/cyb_oko
    environment:
      # Make pip use --user by default.
      PIP_USER: '1'
    ports:
      - 8000:8000
