# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auto_20160713_1508'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('uio_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('registered', models.DateField(auto_now_add=True)),
                ('left', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField(null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.Intern')),
            ],
        ),
        migrations.CreateModel(
            name='InternGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('date_access_given', models.DateField(blank=True, null=True)),
                ('date_access_revoked', models.DateField(blank=True, null=True)),
                ('recieved_interncard', models.BooleanField(default=False)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='intern.Intern')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('access_levels', models.ManyToManyField(to='intern.AccessLevel')),
                ('groups', models.ManyToManyField(related_name='roles', to='intern.InternGroup')),
            ],
        ),
        migrations.AddField(
            model_name='internrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='intern.Role'),
        ),
        migrations.AddField(
            model_name='internrole',
            name='semesters',
            field=models.ManyToManyField(related_name='internroles', to='core.Semester'),
        ),
        migrations.AddField(
            model_name='interncard',
            name='internrole',
            field=models.ManyToManyField(to='intern.InternRole'),
        ),
        migrations.AddField(
            model_name='interncard',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interncard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='internrole',
            unique_together=set([('intern', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='interncard',
            unique_together=set([('intern', 'semester')]),
        ),
    ]
