# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_auto_20161218_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(related_name='roles', to='core.Group'),
        ),
    ]
