# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_auto_20160729_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
