# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_auto_20161218_2255'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='InternGroup',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
