# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20160802_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='internrole',
            name='access_given',
            field=models.BooleanField(default=False),
        ),
    ]
