# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20160714_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='left',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='registered',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 14, 16, 7, 43, 227102, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='interngroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
