# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20160713_1508'),
        ('intern', '0005_auto_20160714_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField(null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.Intern')),
            ],
        ),
        migrations.AddField(
            model_name='internrole',
            name='recieved_interncard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interncard',
            name='internrole',
            field=models.ManyToManyField(to='intern.InternRole'),
        ),
        migrations.AddField(
            model_name='interncard',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interncard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='interncard',
            unique_together=set([('intern', 'semester')]),
        ),
    ]
