# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_auto_20160802_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='journal',
            field=models.TextField(default=''),
        ),
    ]
