# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_intern_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internroles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internrole',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internroles_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
