# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern', '0008_auto_20160802_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='intern',
            name='journal',
        ),
        migrations.AddField(
            model_name='internlogentry',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='intern.Intern'),
        ),
    ]
