# Generated by Django 2.2.9 on 2019-12-31 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0020_auto_20160131_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='råvare',
            name='type',
            field=models.CharField(blank=True, help_text='Type innpakning, f.eks. boks eller fat', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='råvarepris',
            name='antall',
            field=models.PositiveIntegerField(default=1, help_text='Antall dette gir hvor ting kjøpes som pakker, f.eks. six-pack', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='råvare',
            name='enhet',
            field=models.CharField(help_text='Foretrukket enhet for væske er l', max_length=20),
        ),
        migrations.AlterField(
            model_name='råvarepris',
            name='pant',
            field=models.FloatField(default=0),
        ),
    ]
