# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0010_auto_20160315_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='gdpr_approval',
            field=models.BooleanField(default=False, null=True, help_text='Privacy policy agreement'),
        ),
    ]
