# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160713_1508'),
        ('members', '0010_auto_20160315_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('extraordinary', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, to='members.Member')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='generalassembly',
            unique_together=set([('time', 'semester')]),
        ),
    ]
