# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20161119_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalassembly',
            name='minutes',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='generalassembly',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
