# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20161123_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalassembly',
            name='minutes',
            field=models.URLField(default=None, null=True),
        ),
    ]
